name: Nology
favicon: null
layout_spectrum: 0.006004124879837036
typography_spectrum: 0.6461719160433859
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.35535574750974774
  lightness: 0.4300509348977357
  saturation: 0.19171974202618003
  rhythmicContrast: 0.2627878247294575
purpose: []
